---
- name: create user
  ansible.builtin.include_tasks:
    file: user.yml

- name: create docker network
  ansible.builtin.include_tasks:
    file: docker.yml

- name: prepare vm
  ansible.builtin.include_tasks:
    file: vm.yml
